version: '3.8'

services:
  db:
    image: postgres:16-bookworm
    container_name: db
    user: postgres
    restart: always # always restart container if it crashes
    environment:
      - POSTGRES_USER: nicola
      - POSTGRES_PASSWORD: filosi
    ports:
      - '5432:5432'
    networks:
      - nf

  data-pipeline:
    build:
      context: ../../ # Sets docker context to repo root
      dockerfile: projects/data-pipeline/Dockerfile
    working_dir: /projects/data-pipeline
    command:
      - /bin/sh
      - -c
      - make run
        echo "Data pipeline successfully finished running"
    networks:
      - nf
    depends_on:
      - db

networks:
  nf:
    name: nf
    driver: bridge # default network driver for Docker