[tool.poetry]
name = "data-pipeline"
version = "0.1.0"
description = "data pipeline for practice app"
authors = ["Nicola Filosi"]
license = "free"
readme = "README.md"
packages = [{include = "data_pipeline"}]

[tool.poetry.dependencies]
python = "3.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
