name: Reusable CI
run-name: ${{ github.actor }} pushed to ${{ github.ref }}

on:
  workflow_call:

jobs:
  reusable_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.4"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup environment
        working-directory: ./projects/data-pipeline
        run: |
          make install-poetry
          # Source bashrc to sync poetry links
          source ~/.bashrc
          echo "Poetry version is $(poetry --version)" 

      - name: Validate lock file
        working-directory: ./projects/data-pipeline
        run: make validate-lock

      - name: Install python dependencies
        working-directory: ./projects/data-pipeline
        run: make install-deps

      - name: Check linting
        working-directory: ./projects/data-pipeline
        run: make check

      - name: Build Docker image
        working-directory: ./projects/data-pipeline
        run: make build

#      - name: API - Run tests
#        working-directory: ./projects/data-pipeline
#        run: make test