name: CI Data Pipeline
run-name: ${{ github.actor }} pushed to ${{ github.ref }}

on:
  push:
    branches: ["develop", "main"]
    paths:
      - "projects/data-pipeline/**"
  pull_request:
    branches: ["develop", "main"]
    paths:
      - "projects/data-pipeline/**"

  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable_ci.yaml