name: CI Data Pipeline
run-name: ${{ github.actor }} pushed to ${{ github.ref }}

on:
  push:
    branches: ["develop", "main"]
    paths:
      - "projects/data-pipeline/**"
  pull_request:
    branches: ["develop", "main"]
    paths:
      - "projects/data-pipeline/**"

  workflow_dispatch:

jobs:
  data-pipeline-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.4"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup environment
        working-directory: ./projects/data-pipeline
        run: |
          make install-poetry
          # Source bashrc to sync poetry links
          source ~/.bashrc
          echo "Poetry version is $(poetry --version)" 

      - name: Validate lock file
        working-directory: ./projects/data-pipeline
        run: make validate-lock

      - name: API - Install python dependencies
        working-directory: ./projects/data-pipeline
        run: make install-deps

      - name: API - Check formatting
        working-directory: ./projects/data-pipeline
        run: make check

      - name: API - Run tests
        working-directory: ./projects/data-pipeline
        run: make test